== History of software development

.Short History
[plantuml,short-history,align=center]
----
include::plantuml/short-history.puml[]
----

[.notes]
--
* Short talk about project management.
* Complicated to agile. => (kind of)
* Monolithic applications to microservices.
--

== What is Cloud-Native

Definition: Cloud-native software is "highly distributed", must operate in a constantly changing environment, and is itself constantly changing.

[.notes]
--
Source:
DAVIS, CORNELIA (2019). Cloud Native Patterns - DESIGNING CHANGE-TOLERANT SOFTWARE. Shelter Island, NY: Manning Publications Co., p.11
--

=== Key values of cloud-native

==== Requirements

.Cloud Native reqirements
[plantuml,cloud-native-requirements,align=center,svg]
----
include::plantuml/cloud-native-requirements.puml[]
---

[.notes]
--
In this graphics we can see four different requirements that play a big role in cloud native.
All together define what is important to a system to be truly cloud native.

* The first requirement is about always up.
** This brings us to Resilience. A Microservice must be able to recover from a huge number of problems.
*** This means redundancy is needed to be abele to jump in if a accident happens.
*** Adaptability "able to adjust to new conditions" the environment and the software is constantly changing and this must be possible
*** Modularity enables the system to be
**** less complex
**** there for more easy to develop and maintain
**** in case of failure not everything would go down with it
**** improves scaling and redundancy for backup
* As a matter of fact the release frequency increased a lot
** so Agile software fits with agile development is a must and benefits a lot in modern cloud native development.
** Because Agile development work's great with the modular Microservice architecture of cloud native systems
* Anywhere, any device Always up means there are times of high and of low demeaned. To cut coast the system needs to be abele to adapt to the demand and environment.

based on Source:
DAVIS, CORNELIA (2019). Cloud Native Patterns - DESIGNING CHANGE-TOLERANT SOFTWARE. Shelter Island, NY: Manning Publications Co., p.10-12

As before mentioned the number of devices and services services increased over the years so the architecture has to be changed to fit then new needs.
--

=== Reasons for a different type of software

* new requirements and changed user behavior
* changed software development life cycle
* traditional software approaches unsuitable
* new or enhanced technologies like containers

[.notes]
--
Quick recap of previous section
--

=== OpenSource Foundations

.Open technology principles
[plantuml,open-technology-principles,align=center,svg]
----
include::plantuml/open-technology-principles.puml[]
----

[.notes]
--
* Cost
** I can use it without paying, and there is both community and
paid support available.
* Speed
If I use this open source project, it will help me get my job done
quicker.
** Influence
If I find a problem, I can fix it or raise an issue. If I need an
enhancement, I can contribute it or request a new feature.
* Community
** If I have a problem, the community will hopefully help; I don’t
need to open a support ticket. I can also become part of the
community.
* Opportunity
** Significant, diverse open source projects grow larger markets
where there will be demand for my skills.
* License
** Does the open source license permit me to use the software in
the way I’d like to? Many open source projects come with per‐
missive licenses on usage that allow modification, sharing, or
creation of commercial solutions. Some, of course, do not allow
this flexibility.
* Purpose
** Why does the project exist? This goes beyond its technical scope
and covers factors such as why the contributors are
participating.
* Community
** Does the open source project have a vibrant contributor and
user community?
* Standards
** Does the project implement open standard APIs, allowing me to
switch to other providers?
* Governance
** Is the project maintained under an open governance model,
such as those under the Apache Software Foundation, Eclipse
Foundation, or Linux Foundation? We’ll talk more about open
governance later in this chapter.

Source: Charters, G., Daschner, S., Patel, P. & Pool, St. (2019). 
Developing Open Cloud Native Microservices. Sebastopol, CA. O'Rilly Media Inc., p.24-25

The Cloud native computing foundation was created for kubernetes.
--
