@startuml

skinparam timing {
	ArrowColor black

	borderColor #566573
	backgroundColor lightgray
	fontName Calibri
	fontSize 15
	fontColor black
}

concise "Technology" as CTech
concise "Tools" as CToll


/'
@1971
CTech is "Microprocessor"
CToll is {-}

@1972
CTech is {-}
CToll is {-}

@1973
CTech is {-}
CToll is {-}

@1974
CTech is {-}
CToll is {-}

@1975
CTech is {-}
CToll is {-}

@1976
CTech is "Apple 1"
CToll is {-}

@1977
CTech is {-}
CToll is {-}

@1978
CTech is {-}
CToll is {-}

@1979
CTech is {-}
CToll is {-}

@1980
CTech is {-}
CToll is {-}

@1981
CTech is "IBM PC"
CToll is {-}

@1982
CTech is {-}
CToll is "RPC"

@1983
CTech is {-}
CToll is {-}

@1984
CTech is {-}
CToll is {-}

@1985
CTech is {-}
CToll is {-}

@1986
CTech is {-}
CToll is {-}

@1987
CTech is {-}
CToll is {-}

@1988
CTech is {-}
CToll is {-}

@1989
CTech is {-}
CToll is {-}
'/
@1990
CTech is "WWW"
CToll is {-}

@1991
CTech is "Linux"
CToll is {-}

@1992
CTech is {-}
CToll is {-}

@1993
CTech is {-}
CToll is {-}

@1994
CTech is {-}
CToll is {-}

@1995
CTech is {-}
CToll is {-}

@1996
CTech is {-}
CToll is {-}

@1997
CTech is "Google"
CToll is {-}

@1998
CTech is {-}
CToll is {-}

@1999
CTech is {-}
CToll is "SOAP \n REST"

@2000
CTech is {-}
CToll is {-}

@2001
CTech is "VMware"
CToll is {-}

@2002
CTech is {-}
CToll is {-}

@2003
CTech is {-}
CToll is {-}

@2004
CTech is "Eclipse Found. \n Facebook"
CToll is {-}

@2005
CTech is "YouTube"
CToll is {-}

@2006
CTech is "Twitter \n AWS"
CToll is {-}

@2007
CTech is {-}
CToll is {-}

@2008
CTech is "Netflix"
CToll is "LXC"

@2009
CTech is {-}
CToll is {-}

@2010
CTech is {-}
CToll is {-}

@2011
CTech is {-}
CToll is {-}

@2012
CTech is {-}
CToll is {-}

@2013
CTech is {-}
CToll is "Docker"

@2014
CTech is {-}
CToll is "Kubernetes"

@2015
CTech is "CNCF"
CToll is "GraphQL"

@2016
CTech is {-}
CToll is {-}

@2017
CTech is "MicroProfile"
CToll is {-}

@2018
CTech is "Quarkus"
CToll is {-}

@2019
CTech is {-}
CToll is {-}
/'
@2020
CTech is "MicroProfile \n 4"
CToll is {-}
'/

@enduml
